### ISSUE TITLE
How to disable lzo compression?

### ISSUE THREAD

**Issue by gdhbashton** [thejandroman/puppet-openvpn_client#1]
What lovely timing - I just had a need for exactly this module yesterday :)

I need to communicate with a WatchGuard router which does not support LZO compression. Setting `comp-lzo no` simply doesn't work - I get LZO errors in syslog. I must omit the `comp-lzo` line entirely.

I see the following in the ERB template:

```
<%- unless @comp_lzo.nil? -%>
comp-lzo <%= @comp_lzo %>
<%- end -%>
```

How do I set the `comp_lzo` parameter to `nil` given it must satisfy `validate_string()` ?

**Comment by thejandroman** [comment]
Great catch! This is a bug...

The intention of the module is to be able to provide `undef` to any of the parameters and not have them appear in the template. The `validate_*` functions obviously stop this from being the case.

I'll have a new version of the module pushed shortly.

**Comment by thejandroman** [comment]
Turns out I spoke too soon when I said I had fixed this...

**Comment by gdhbashton** [comment]
Thank you :) 

I had a much more naive approach used in my own branch . https://github.com/gdhbashton/puppet-openvpn_client/commit/1bdc2867d8d5f3ddcd8e91635a8da6efde039d71 but I'd always rather pick up an upstream version especially now it's on the Forge.
